# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install hexo-cli -g
      - run: npm install
      - run: git clone https://github.com/YunYouJun/hexo-theme-yun themes/hexo-theme-yun
      - run: export TENCENT_ID=${{ secrets.TENCENT_ID }}
      - run: export TENCENT_KEY=${{ secrets.TENCENT_KEY }}
      - run: hexo g&&hexo d
